// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic
{

    // AomFieldObject
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class AomFieldObject
    {
        public System.Guid Id { get; set; } // ID (Primary key)
        public System.Guid AomObjectId { get; set; } // AomObjectId
        public System.Guid AomFieldMetaId { get; set; } // AomFieldMetaId
        public string Value { get; set; } // Value (length: 250)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<RelationshipObject> FkAomFieldObject { get; set; } // RelationshipObject.FK_dbo.RelationshipObject_dbo.AomFieldObject_FkAomFieldObjectId
        public virtual System.Collections.Generic.ICollection<RelationshipObject> PkAomFieldObject { get; set; } // RelationshipObject.FK_dbo.RelationshipObject_dbo.AomFieldObject_PkAomFieldObjectId

        // Foreign keys
        public virtual AomFieldMeta AomFieldMeta { get; set; } // FK_dbo.AomFieldObject_dbo.AomFieldMeta_AomFieldMetaId
        public virtual AomObject AomObject { get; set; } // FK_dbo.AomFieldObject_dbo.AomObject_AomObjectId

        public AomFieldObject()
        {
            Id = System.Guid.NewGuid();
            FkAomFieldObject = new System.Collections.Generic.List<RelationshipObject>();
            PkAomFieldObject = new System.Collections.Generic.List<RelationshipObject>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
