// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic
{

    // AomFieldMeta
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class AomFieldMetaMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AomFieldMeta>
    {
        public AomFieldMetaMap()
            : this("dbo")
        {
        }

        public AomFieldMetaMap(string schema)
        {
            ToTable("AomFieldMeta", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.AomMetaId).HasColumnName(@"AomMetaId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(250);
            Property(x => x.FieldTypeId).HasColumnName(@"FieldTypeId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.Display).HasColumnName(@"Display").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(250);

            // Foreign keys
            HasRequired(a => a.AomMeta).WithMany(b => b.AomFieldMetas).HasForeignKey(c => c.AomMetaId); // FK_dbo.AomFieldMeta_dbo.AomMeta_AomMetaId
            HasRequired(a => a.FieldType).WithMany(b => b.AomFieldMetas).HasForeignKey(c => c.FieldTypeId); // FK_dbo.AomFieldMeta_dbo.FieldTypes_FieldTypeId
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
