// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic
{

    // AomMeta
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class AomMeta
    {
        public System.Guid Id { get; set; } // ID (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public string Display { get; set; } // Display (length: 100)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<AomFieldMeta> AomFieldMetas { get; set; } // AomFieldMeta.FK_dbo.AomFieldMeta_dbo.AomMeta_AomMetaId
        public virtual System.Collections.Generic.ICollection<AomObject> AomObjects { get; set; } // AomObject.FK_dbo.AomObject_dbo.AomMeta_AomMetaId
        public virtual System.Collections.Generic.ICollection<RelationshipMeta> FkAomMeta { get; set; } // RelationshipMeta.FK_dbo.RelationshipMeta_dbo.AomMeta_FkAomMetaId
        public virtual System.Collections.Generic.ICollection<RelationshipMeta> PkAomMeta { get; set; } // RelationshipMeta.FK_dbo.RelationshipMeta_dbo.AomMeta_PkAomMetaId

        public AomMeta()
        {
            Id = System.Guid.NewGuid();
            Display = "";
            AomFieldMetas = new System.Collections.Generic.List<AomFieldMeta>();
            AomObjects = new System.Collections.Generic.List<AomObject>();
            FkAomMeta = new System.Collections.Generic.List<RelationshipMeta>();
            PkAomMeta = new System.Collections.Generic.List<RelationshipMeta>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
