// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61

using System;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic
{

    // AomObject
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class AomObject
    {
        public System.Guid Id { get; set; } // ID (Primary key)
        public System.Guid AomMetaId { get; set; } // AomMetaId
        public string Name { get; set; } // Name (length: 250)

        // Reverse navigation
        public virtual System.Collections.Generic.List<AomFieldObject> AomFieldObjects { get; set; } // AomFieldObject.FK_dbo.AomFieldObject_dbo.AomObject_AomObjectId

        // Foreign keys
        public virtual AomMeta AomMeta { get; set; } // FK_dbo.AomObject_dbo.AomMeta_AomMetaId

        public AomObject()
        {
            Id = Guid.NewGuid();
            AomFieldObjects = new System.Collections.Generic.List<AomFieldObject>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
