// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61

using System;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic
{

    // FieldTypes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class FieldType
    {
        public System.Guid Id { get; set; } // ID (Primary key)
        public string Name { get; set; } // Name (length: 50)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<AomFieldMeta> AomFieldMetas { get; set; } // AomFieldMeta.FK_dbo.AomFieldMeta_dbo.FieldTypes_FieldTypeId

        public FieldType()
        {
            Id = Guid.NewGuid();
            AomFieldMetas = new System.Collections.Generic.List<AomFieldMeta>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
