// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic
{

    public interface IAomDbContext : System.IDisposable
    {
        System.Data.Entity.DbSet<AomFieldMeta> AomFieldMetas { get; set; } // AomFieldMeta
        System.Data.Entity.DbSet<AomFieldObject> AomFieldObjects { get; set; } // AomFieldObject
        System.Data.Entity.DbSet<AomMeta> AomMetas { get; set; } // AomMeta
        System.Data.Entity.DbSet<AomObject> AomObjects { get; set; } // AomObject
        System.Data.Entity.DbSet<FieldType> FieldTypes { get; set; } // FieldTypes
        System.Data.Entity.DbSet<RelationshipMeta> RelationshipMetas { get; set; } // RelationshipMeta
        System.Data.Entity.DbSet<RelationshipObject> RelationshipObjects { get; set; } // RelationshipObject

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
