// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic
{

    // RelationshipObject
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class RelationshipObject
    {
        public System.Guid Id { get; set; } // ID (Primary key)
        public System.Guid RelationshipMetaId { get; set; } // RelationshipMetaId
        public System.Guid PkAomFieldObjectId { get; set; } // PkAomFieldObjectId
        public System.Guid FkAomFieldObjectId { get; set; } // FkAomFieldObjectId

        // Foreign keys
        public virtual AomFieldMeta AomFieldMeta { get; set; } // FK_dbo.RelationshipObject_dbo.AomFieldMeta_FkAomFieldObjectId
        public virtual AomFieldObject FkAomFieldObject { get; set; } // FK_dbo.RelationshipObject_dbo.AomFieldObject_FkAomFieldObjectId
        public virtual AomFieldObject PkAomFieldObject { get; set; } // FK_dbo.RelationshipObject_dbo.AomFieldObject_PkAomFieldObjectId

        public RelationshipObject()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
