// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic
{

    // RelationshipObject
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class RelationshipObjectMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RelationshipObject>
    {
        public RelationshipObjectMap()
            : this("dbo")
        {
        }

        public RelationshipObjectMap(string schema)
        {
            ToTable("RelationshipObject", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.RelationshipMetaId).HasColumnName(@"RelationshipMetaId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.PkAomFieldObjectId).HasColumnName(@"PkAomFieldObjectId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.FkAomFieldObjectId).HasColumnName(@"FkAomFieldObjectId").HasColumnType("uniqueidentifier").IsRequired();

            // Foreign keys
            HasRequired(a => a.AomFieldMeta).WithMany(b => b.RelationshipObjects).HasForeignKey(c => c.FkAomFieldObjectId).WillCascadeOnDelete(false); // FK_dbo.RelationshipObject_dbo.AomFieldMeta_FkAomFieldObjectId
            HasRequired(a => a.FkAomFieldObject).WithMany(b => b.FkAomFieldObject).HasForeignKey(c => c.FkAomFieldObjectId).WillCascadeOnDelete(false); // FK_dbo.RelationshipObject_dbo.AomFieldObject_FkAomFieldObjectId
            HasRequired(a => a.PkAomFieldObject).WithMany(b => b.PkAomFieldObject).HasForeignKey(c => c.PkAomFieldObjectId).WillCascadeOnDelete(false); // FK_dbo.RelationshipObject_dbo.AomFieldObject_PkAomFieldObjectId
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
