// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61

using System;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic
{

    // RelationshipMeta
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class RelationshipMeta
    {
        public System.Guid Id { get; set; } // ID (Primary key)
        public System.Guid PkAomMetaId { get; set; } // PkAomMetaId
        public System.Guid FkAomMetaId { get; set; } // FkAomMetaId
        public System.Guid FkAomFieldMetaId { get; set; } // FkAomFieldMetaId
        public string Name { get; set; } // Name (length: 150)
        public System.Guid PkAomFieldMetaId { get; set; } // PkAomFieldMetaId

        // Foreign keys
        public virtual AomFieldMeta FkAomFieldMeta { get; set; } // FK_dbo.RelationshipMeta_dbo.AomFieldMeta_FkAomFieldMetaId
        public virtual AomFieldMeta PkAomFieldMeta { get; set; } // FK_RelationshipMeta_AomFieldMeta
        public virtual AomMeta FkAomMeta { get; set; } // FK_dbo.RelationshipMeta_dbo.AomMeta_FkAomMetaId
        public virtual AomMeta PkAomMeta { get; set; } // FK_dbo.RelationshipMeta_dbo.AomMeta_PkAomMetaId

        public RelationshipMeta()
        {
            Id = Guid.NewGuid();
            Name = "";
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
